add maven and sbt, add scala autocomplete support for emacs, add html autocomplete support

diff --git a/devenv/Dockerfile b/devenv/Dockerfile
--- a/devenv/Dockerfile
+++ b/devenv/Dockerfile
@@ -3,10 +3,15 @@ MAINTAINER Marios Andreopoulos <opensource@andmarios.com>
 
 RUN yum install -y epel-release deltarpm && \
     yum -y update && \
+    curl https://bintray.com/sbt/rpm/rpm | \
+        tee /etc/yum.repos.d/bintray-sbt-rpm.repo && \
+    curl https://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo | \
+        tee /etc/yum.repos.d/epel-apache-maven.repo && \
     yum install -y git golang java-1.7.0-openjdk-headless \
         java-1.7.0-openjdk-devel nano emacs-nox wget net-tools gcc jq ncftp \
         tar moreutils docker bash-completion ansible sudo bind-utils mlocate \
-        python-libcloud pyOpenSSL htop nload iftop vim-enhanced && \
+        python-libcloud pyOpenSSL htop nload iftop vim-enhanced ruby rubygems \
+        sbt apache-maven && \
     /etc/cron.daily/mlocate && \
     echo "progress = dot:mega" | tee /etc/wgetrc
 
@@ -39,12 +44,19 @@ USER dev
 WORKDIR /home/dev
 
 ENV HOME="/home/dev" GOPATH="/home/dev/.go"
-RUN go get -u -v github.com/nsf/gocode
+# This is too slow to have to rebuild.
+RUN sbt exit
 # Emacs will probably exit with an error code ≠ 0 but we do not care.
-RUN emacs --kill --daemon || echo "Unimportant Error"
-RUN mkdir -p ~/.vim/autoload ~/.vim/bundle && \
+RUN go get -u -v github.com/nsf/gocode
+    emacs --kill --daemon || echo "Unimportant Error" && \
+    mkdir -p ~/.vim/autoload ~/.vim/bundle && \
     curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim && \
     git clone https://github.com/fatih/vim-go.git ~/.vim/bundle/vim-go && \
-    .go/src/github.com/nsf/gocode/vim/pathogen_update.sh
+    ~/.go/src/github.com/nsf/gocode/vim/pathogen_update.sh && \
+    git clone https://github.com/derekwyatt/vim-scala.git \
+        ~/.vim/bundle/vim-scala && \
+    mkdir -p ~/.sbt/0.13/plugins/ && \
+    echo 'addSbtPlugin("org.ensime" % "ensime-sbt" % "0.1.6")' >> \
+        ~/.sbt/0.13/plugins/plugins.sbt
 
 CMD ["bash"]
